version: "3.8"
services:
  api.e2e:
    build:
      context: .
      dockerfile: ./build/local/Dockerfile.e2e
    volumes:
      - .:/usr/src/api
    ports:
      - "4001:4000"
    env_file:
      - .env.e2e
    networks:
      - node-nw

  mysql.e2e:
    image: mysql:8.1.0
    platform: linux/amd64
    ports:
      - "3307:3306"
    volumes:
      - ./build/local/mysql/:/etc/mysql/conf.d/:ro
      - mysql_data_e2e:/var/lib/mysql
    env_file:
      - .env.e2e
    networks:
      - node-nw

volumes:
  mysql_data_e2e: null

networks:
  node-nw:
    external: true